[build]
builder = "nixpacks"
watchPatterns = [
  "backend/**/*",
  "!frontend/**/*"
]
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[env]
PYTHONPATH = "/app"
PYTHONUNBUFFERED = "1"

[nixpacks]
# Specify Python version
pythonVersion = "3.9"